baseURL: "/"
disablePathToLower: true
languageCode: en-us
title: Cesar
theme: jane
googleAnalytics: UA-110580110-1 
disqusShortname: cesar
enableRobotsTXT: true
defaultContentLanguage: en
enableEmoji: true


PygmentsCodeFences: true 
PygmentsUseClasses: true
PygmentsCodefencesGuessSyntax: true
PygmentsOptions: linenos=table

copyright: Cesar Valdez           

menu:
  main:
  - text: writing
    name: Writing
    link: /post 
    url: /post/
  - text: about 
    name: About
    link: /about 
    url: /about/
  - text: code 
    name: Code
    url:  https://github.com/cesarvr 
    link: https://github.com/cesarvr 

params: 
  social:
    c-twitter: https://twitter.com/cvaldezr 
    e-linkedin: https://linkedin.com/in/cesarvr 




