baseURL = "https://cesarvr.io"
languageCode = "en-us"
title = "Happy Hacking"
theme = "bare"
enableGitInfo = true


[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["post"]
author = "Cesar"
email = "cesarv01@yahoo.com"
description = 'Programmer & Openshift Hacker'
# PostCSS is harder than it should be to get working on a theme
# example site. It's easy on _your_ site.
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true
disableAttribution = true

[[params.social]]
icon = "github-circle"
url = "https://github.com/cesarvr"

[[params.social]]
icon = "linkedin"
url = "https://www.linkedin.com/in/cesarvr/"