baseURL: "/"
disablePathToLower: true
languageCode: en-us
title: code_scripter
theme: hugo-paper
enableRobotsTXT: true
defaultContentLanguage: en
enableEmoji: true

params:
  author: Cesar Valdez
  description: Crafting Beautiful Software

PygmentsUseClasses: true
PygmentsCodefencesGuessSyntax: true
PygmentsOptions: linenos=table



menu:
  main:
  - text: writing
    name: Writing
    link: /post
    url: /post/
  - text: about
    name: About
    link: /about
    url: /about/
  - name: "Categories"
    weight: 40
    identifier: "categories"
    url: "categories/"
  - text: code
    name: Code
    url:  https://github.com/cesarvr
    link: https://github.com/cesarvr
